spring:
  output:
    ansi:
      enabled: ALWAYS
#  profiles:
#    active: company # company notebook
  thymeleaf:
    enabled: true #
    cache: false #
    check-template-location: true # Check that the templates location exists.
    #content-type: text/html #
    encoding: UTF-8 #
    prefix: classpath:/templates/ #
    suffix: .html #
    #
    mode: HTML #LEGACYHTML5
  devtools:
    restart:
      enabled: true
