spring:
  profiles:
    active: company # company notebook
  output:
    ansi:
      enabled: ALWAYS
#  profiles:
#    active: company # company notebook
  thymeleaf:
    enabled: true #是否为Web框架启用Thymeleaf视图解析
    cache: false # 缓存设定 开发时使用false 运行使用true
    check-template: true #是否在呈现模板之前检查模板是否存在
    check-template-location: true #检查模板位置是否正确(默认值:true)
    enable-spring-el-compiler: false #在SpringEL表达式中启用SpringEL编译器
    #content-type: text/html # text/html
    encoding: UTF-8 # 默认编码UTF-8
    prefix: classpath:/templates/ #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    suffix: .html # .html
    #不强制关闭HTML标签
    mode: HTML5 #要运用于模板之上的模板模式。另见TemplateMode(默认值：HTML5)
  devtools:
    restart:
      enabled: true
